volumes:
  database:
networks:
  backend_network:
    ipam:
      config:
        - subnet: 172.80.0.1/16
          gateway: 172.80.0.1
services:
  database:
    container_name: database
    image: "postgres:latest"
    networks:
      backend_network:
        ipv4_address: 172.80.0.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ./
    networks:
      backend_network:
        ipv4_address: 172.80.0.3
    ports:
      - 8080:8080