POST http://localhost:8080/api/blog
Content-Type: application/json

{
  "title": "Hello",
  "body": "Hello World",
  "authorID": 1
}

###
GET http://localhost:8080/api/blog/all

###
PUT http://localhost:8080/api/blog
Content-Type: application/json

{
  "id": 9,
  "title": "Hello",
  "body": "Hello Worlds"
}

###
DELETE http://localhost:8080/api/blog?id=4